### ISSUE TITLE
遇到无法启动bug

### ISSUE THREAD

**Issue by livingbody** [QPT-Family/QWebSiteOptimizer#2]
遇到无法启动bug
`(p2) PS C:\Users\livingbody> python -m qwebsite -g Flase
当前操作系统： Windows
Traceback (most recent call last):
  File "C:\Users\livingbody\miniconda3\envs\p2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\livingbody\miniconda3\envs\p2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\livingbody\miniconda3\envs\p2\lib\site-packages\qwebsite\__main__.py", line 34, in <module>
    cli([])
  File "C:\Users\livingbody\miniconda3\envs\p2\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\livingbody\miniconda3\envs\p2\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\livingbody\miniconda3\envs\p2\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\livingbody\miniconda3\envs\p2\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\livingbody\miniconda3\envs\p2\lib\site-packages\qwebsite\__main__.py", line 25, in cli
    QWebSiteOptGUI().run()
  File "C:\Users\livingbody\miniconda3\envs\p2\lib\site-packages\qwebsite\submethod\github.py", line 95, in __init__
    self.gui = CreateQGUI(title=title)
  File "C:\Users\livingbody\miniconda3\envs\p2\lib\site-packages\qgui\factory.py", line 52, in __init__
    self.root.style = Style(**QStyle.default)
  File "C:\Users\livingbody\miniconda3\envs\p2\lib\site-packages\ttkbootstrap\__init__.py", line 81, in __init__
    self._load_themes(themes_file)
  File "C:\Users\livingbody\miniconda3\envs\p2\lib\site-packages\ttkbootstrap\__init__.py", line 119, in _load_themes
    themetype=settings['type'],
TypeError: list indices must be integers or slices, not str`

**Comment by GT-ZhangAcer** [comment]
新版本已经解决啦~
